//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.

// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Text;

namespace OpenAuth.Repository.Domain
{
    /// <summary>
	/// 班级信息表
	/// </summary>
    public partial class Class : Entity
    {
        public Class()
        {
            this.ClassNick = 0;
            this.ClassName = string.Empty;
            this.GetinDate = Convert.ToDateTime("1900-01-01");
            this.Department = string.Empty;
            this.Major = string.Empty;
            this.Monitor = string.Empty;
            this.MonitorGUID = Guid.Empty;
            this.SummaryStus = 0;
            this.Tutor = string.Empty;
            this.ClassNum = 0;
        }
        /// <summary>
        /// 班级代号
        /// </summary>
        public int ClassNick { get; set; }
        /// <summary>
        /// 班级名
        /// </summary>
        public string ClassName { get; set; }
        /// <summary>
        /// 入学时间
        /// </summary>
        public DateTime GetinDate { get; set; }
        /// <summary>
        /// 所在系部
        /// </summary>
        public string Department { get; set; }
        /// <summary>
        /// 专业
        /// </summary>
        public string Major { get; set; }
        /// <summary>
        /// 班长
        /// </summary>
        public string Monitor { get; set; }
        /// <summary>
        /// 班长联系信息
        /// </summary>
        public Guid MonitorGUID{ get; set; }
        /// <summary>
        /// 班级人数
        /// </summary>
        public int SummaryStus { get; set; }
        /// <summary>
        /// 导员
        /// </summary>
        public string Tutor { get; set; }
        /// <summary>
        /// 班级
        /// </summary>
        public int ClassNum { get; set; }
    }
}