//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.

// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Text;

namespace OpenAuth.Repository.Domain
{
    /// <summary>
	/// 库存信息表
	/// </summary>
    public partial class Inventory : Entity
    {
        public Inventory()
        {
            this.TextbookName = string.Empty;
            this.OutputName = string.Empty;
            this.Author = string.Empty;
            this.MajorFor = string.Empty;
            this.BookUnit = string.Empty;
            this.TextbookNum = 0;
            this.Remarks = string.Empty;
            this.GetInDate = Convert.ToDateTime("1900-01-01");
            this.GetOutDate = Convert.ToDateTime("1900-01-01");
            this.BookDate = Convert.ToDateTime("1900-01-01");
            this.FRIDNum = string.Empty;
            this.ReceivedBy = string.Empty;
        }
        /// <summary>
        /// 
        /// </summary>
        public string TextbookName { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string OutputName { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string Author { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string MajorFor { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string BookUnit { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public int? TextbookNum { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string Remarks { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public DateTime? GetInDate { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public DateTime? GetOutDate { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public DateTime? BookDate { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string FRIDNum { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string ReceivedBy { get; set; }

    }
}