//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a CodeSmith Template.
//
//     DO NOT MODIFY contents of this file. Changes to this
//     file will be lost if the code is regenerated.

// </autogenerated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Text;

namespace OpenAuth.Repository.Domain
{
    /// <summary>
	/// 教师信息表
	/// </summary>
    public partial class Teacher : Entity
    {
        public Teacher()
        {
            this.TeacherNum = 0;
            this.TeacherName = string.Empty;
            this.Gender = string.Empty;
            this.Department = string.Empty;
        }
        /// <summary>
        /// 教师编号
        /// </summary>
        public int TeacherNum { get; set; }
        /// <summary>
        /// 教师名称
        /// </summary>
        public string TeacherName { get; set; }
        /// <summary>
        /// 性别
        /// </summary>
        public string Gender { get; set; }
        /// <summary>
        /// 所在系部
        /// </summary>
        public string Department { get; set; }
    }
}